import Link from "next/link";

export default function LegalPage() {
  return (
    <div className="policy-container">
      <div className="policy-paper">
        <Link href="/" className="back-link">
          <i className="fas fa-arrow-left"></i> Back
        </Link>
        <h1>Legal & Compliance</h1>
        <h2>Project Status</h2>
        <p>
          AtlasFlux is a personal project built by Muhammad Nabil. It is not a
          registered business entity under the Companies Commission of Malaysia
          (SSM) and does not engage in commercial trading or the sale of
          services.
        </p>
        <h2>Intellectual Property</h2>
        <p>
          All original code, UI designs, and the “AtlasFlux” brand are owned by
          the developer. You may not reproduce or distribute any part of the
          platform without explicit permission.
        </p>
        <h2>Regulatory Compliance</h2>
        <p>
          I strive to adhere to the Personal Data Protection Act (PDPA) 2010 of
          Malaysia and the Communications and Multimedia Act 1998, ensuring a
          safe and ethical digital space.
        </p>
        <h2>Third‑Party Licenses</h2>
        <p>
          AtlasFlux AI aggregates models from OpenRouter and Replicate. Each
          model is subject to its own license terms. You are responsible for
          complying with the applicable licenses when using outputs generated by
          these models. For more information, please refer to the{" "}
          <a
            href="https://openrouter.ai/terms"
            target="_blank"
            rel="noopener noreferrer"
          >
            OpenRouter Terms
          </a>{" "}
          and{" "}
          <a
            href="https://replicate.com/terms"
            target="_blank"
            rel="noopener noreferrer"
          >
            Replicate Terms
          </a>
          .
        </p>
        <h2>Policy Summaries</h2>
        <p>Brief overview of key policies:</p>
        <ul>
          <li>
            <strong>AI Disclaimer:</strong> Use AI at your own risk. Outputs may
            be inaccurate. Always verify.
          </li>
          <li>
            <strong>Terms & Conditions:</strong> Rules for using the platform
            and credit system.
          </li>
          <li>
            <strong>Privacy Policy:</strong> What data we collect and how it is
            used.
          </li>
          <li>
            <strong>Refund Policy:</strong> Automatic refunds for failed
            generations; no refunds for purchases.
          </li>
          <li>
            <strong>Ban Policy:</strong> Zero tolerance for explicit content,
            harassment, or abuse.
          </li>
          <li>
            <strong>Image Generation Policy:</strong> Copyright, prohibited
            content, and moderation.
          </li>
        </ul>
      </div>
    </div>
  );
}
