import Link from "next/link";

export default function LegalPage() {
  return (
    <div className="policy-container">
      <div className="policy-text">
        <Link href="/" className="back-btn">
          <i className="fas fa-arrow-left"></i> Back
        </Link>
        <h1>Legal & Compliance</h1>
        <h2>Project Status</h2>
        <p>
          AtlasFlux is a personal project built by Muhd Nabil, a solo developer.
          It is not a registered business entity under the Companies Commission
          of Malaysia (SSM) and does not engage in commercial trading or the
          sale of services.
        </p>
        <h2>Intellectual Property</h2>
        <p>
          All original code, UI designs, and the “AtlasFlux” brand are owned by
          the developer. You may not reproduce or distribute any part of the
          platform without explicit permission.
        </p>
        <h2>Regulatory Compliance</h2>
        <p>
          I strive to adhere to the Personal Data Protection Act (PDPA) 2010 of
          Malaysia and the Communications and Multimedia Act 1998, ensuring a
          safe and ethical digital space.
        </p>
        <h2>Third‑Party Licenses</h2>
        <p>
          AtlasFlux AI aggregates models from OpenRouter and Replicate. Each
          model is subject to its own license terms. You are responsible for
          complying with the applicable licenses when using outputs generated by
          these models. For more information, please refer to the{" "}
          <a
            href="https://openrouter.ai/terms"
            target="_blank"
            rel="noopener noreferrer"
          >
            OpenRouter Terms
          </a>{" "}
          and{" "}
          <a
            href="https://replicate.com/terms"
            target="_blank"
            rel="noopener noreferrer"
          >
            Replicate Terms
          </a>
          .
        </p>
      </div>
    </div>
  );
}
