import Link from "next/link";

export default function DisclaimerPage() {
  return (
    <div className="policy-container">
      <div className="policy-paper">
        <Link href="/" className="back-link">
          <i className="fas fa-arrow-left"></i> Back
        </Link>
        <h1>Disclaimer</h1>
        <h2>AI Content Disclosure</h2>
        <p>
          All content generated by AtlasFlux AI (ai.atlasflux.my) is produced by
          third‑party large language models accessed through OpenRouter and
          Replicate. While I strive to provide accurate and helpful responses,
          AI models are known to sometimes produce incorrect, misleading, or
          biased information (often called “hallucinations”).
        </p>
        <h2>1. Accuracy of Information</h2>
        <p>
          I make no guarantees regarding the accuracy, completeness, or
          reliability of any AI‑generated content. You are solely responsible
          for verifying any information obtained through the platform,
          especially in technical, legal, or financial contexts.
        </p>
        <h2>2. User Responsibility</h2>
        <p>
          The use of any information provided by AtlasFlux is at your own risk.
          I shall not be held liable for any loss, damage, or consequence
          resulting from decisions made based on AI outputs.
        </p>
        <h2>3. No Professional Advice</h2>
        <p>
          Content provided is for informational and educational purposes only.
          It does not constitute professional, legal, medical, or financial
          advice.
        </p>
      </div>
    </div>
  );
}
